baseURL = "https://galleon.github.io"
languageCode = "en-us"
title = "Tog's website"
theme = "hugo-coder"

paginate = 20
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = "guillaumealleon"
googleAnalytics = ""

[params]
    author = "Guillaume Alleon"
    info = ""
    description = "Tog's website"
    keywords = "blog,developer,personal"
    avatarurl = "/img/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footerContent = "Enter a nice text here"

    hideFooter = true
    hideCredits = false
    hideCopyright = false

    rtl = false

    math = true

    colorScheme = "auto"
    hideColorSchemeToggle = false

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
    author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/galleon/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/galleon/"
[[params.social]]
    name = "Medium"
    icon = "fa fa-medium"
    weight = 3
    url = ""

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
